### ISSUE TITLE
1.1.6 Obsidian seeds can't be reprocessed

### ISSUE THREAD

**Issue by LeCuek** [AlexSa1000/MysticalAgriculture-Refabricated#3]
When putting obsidian seeds in a seed reprocessor, nothing happens, and no recipe is found on Roughly Enough Items

https://user-images.githubusercontent.com/46426142/122209105-6c305f80-cea4-11eb-887f-adc4fff359b1.mp4

**Comment by AlexSa1000** [comment]
Fixed in 1.1.7
